#
mv ABC.MKF abc.mkf
mv BALL.MKF ball.mkf
mv DATA.MKF data.mkf
mv F.MKF f.mkf
mv FBP.MKF fbp.mkf
mv FIRE.MKF fire.mkf
mv GOP.MKF gop.mkf
mv INSTALL.EXE install.exe
mv JIANTI.FON jianti.fon
mv JS3.EXE js3.exe
mv M.MSG m.msg
mv MAP.MKF map.mkf
mv MGO.MKF mgo.mkf
mv MIDI.MKF midi.mkf
mv MPU401.DRV mpu401.drv
mv MUS.MKF mus.mkf
mv PAL!.EXE pal!.exe
mv PAL.EXE pal.exe
mv PAL.JS3 pal.js3
mv PALS!.EXE pals!.exe
mv PALS.EXE pals.exe
mv PAT.MKF pat.mkf
mv PLAY.BAT play.bat
mv RGM.MKF rgm.mkf
mv RNG.MKF rng.mkf
mv SAVES saves
mv SETUP.DAT setup.dat
mv SSS.MKF sss.mkf
mv VOC.MKF voc.mkf
mv WOR16.ASC wor16.asc
mv WOR16.FON wor16.fon
mv WORD.DAT word.dat
